services:
  dotnet-function-app:
    build:
      context: ../WebScrapper
      dockerfile: ../WebScrapper/Dockerfile
    environment:
      - ConnectionStrings__MongoUrl=
      - SmtpSettings__SenderEmail=
      - SmtpSettings__SenderPassword=
      - SmtpSettings__SmtpHost=
      - SmtpSettings__SmtpPort=
      - SmtpSettings__SecureSocketOptions=
    ports:
      - "8080:80" # Map the port as needed for local testing
